"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";

const ACCENT = "#C8FF00"; const CYAN = "#00E5FF"; const PURPLE = "#A855F7";

const FEATURES = [
  { icon: "⬡", title: "Health Diagnostics", desc: "Deep 5-dimension analysis across market, execution, finance, growth, and competition.", color: ACCENT, stat: "5 dimensions" },
  { icon: "◎", title: "Burn Rate Simulator", desc: "Model your runway in real-time. Compare scenarios A vs B and find the optimal burn rate.", color: CYAN, stat: "36-month model" },
  { icon: "★", title: "Pitch Deck AI", desc: "Generate a full investor-ready pitch deck in seconds. Tailored tone for investors, customers, or partners.", color: "#FFB800", stat: "10 slides, 3 tones" },
  { icon: "⊕", title: "Competitor Intel", desc: "Deep-dive on any competitor. Threat scores, radar charts, your edge — all generated by AI.", color: PURPLE, stat: "6-axis analysis" },
  { icon: "◈", title: "OKR Engine", desc: "Auto-generate a full year of OKRs tailored to your stage, team size, and health scores.", color: "#FF6B35", stat: "4 quarters, 12 KRs" },
  { icon: "🔥", title: "Progress Tracker", desc: "Weekly check-in streaks, score history, achievements. Build the habit of measuring what matters.", color: "#FF6B35", stat: "10 achievements" },
];

const STATS = [
  { value: "5", label: "Analysis Dimensions" }, { value: "10+", label: "AI-Powered Features" },
  { value: "36mo", label: "Runway Modeling" }, { value: "∞", label: "Scenarios to Explore" },
];

const TESTIMONIALS = [
  { quote: "Cortiq told us our execution score was 34. We fixed our hiring plan and raised our seed in 6 weeks.", name: "Arjun M.", role: "Founder, DevFlow", avatar: "A", color: ACCENT },
  { quote: "The OKR generator alone saved us 3 planning sessions. It just knows what a Series A startup needs.", name: "Priya K.", role: "CEO, NestScale", avatar: "P", color: CYAN },
  { quote: "I run an analysis every Monday. My health score went from 41 to 78 in 3 months.", name: "Dani R.", role: "Co-founder, Loopstack", avatar: "D", color: PURPLE },
];

const ROTATING_WORDS = ["Intelligence", "Diagnostics", "Clarity", "Advantage", "Readiness"];

export default function LandingPage() {
  const router = useRouter();
  const [tick, setTick] = useState(0);
  const [mousePos, setMousePos] = useState({ x: 0, y: 0 });
  const [scrollY, setScrollY] = useState(0);
  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    const interval = setInterval(() => setTick(t => t + 1), 2000);
    return () => clearInterval(interval);
  }, []);

  useEffect(() => {
    const check = () => setIsMobile(window.innerWidth < 768);
    check(); window.addEventListener("resize", check);
    const handleMouse = (e: MouseEvent) => setMousePos({ x: e.clientX, y: e.clientY });
    const handleScroll = () => setScrollY(window.scrollY);
    window.addEventListener("mousemove", handleMouse);
    window.addEventListener("scroll", handleScroll);
    return () => { window.removeEventListener("resize", check); window.removeEventListener("mousemove", handleMouse); window.removeEventListener("scroll", handleScroll); };
  }, []);

  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Space+Mono:ital,wght@0,400;0,700;1,400&family=Syne:wght@700;800&family=DM+Serif+Display:ital@0;1&display=swap');
        *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
        html { scroll-behavior: smooth; }
        body { background: #050505; color: white; overflow-x: hidden; }
        ::-webkit-scrollbar { width: 3px; } ::-webkit-scrollbar-thumb { background: #1a1a1a; }
        @keyframes fadeUp { from{opacity:0;transform:translateY(24px)} to{opacity:1;transform:translateY(0)} }
        @keyframes scanline { 0%{transform:translateY(-100%)} 100%{transform:translateY(100vh)} }
        @keyframes float { 0%,100%{transform:translateY(0)} 50%{transform:translateY(-12px)} }
        @keyframes glowPulse { 0%,100%{box-shadow:0 0 20px ${ACCENT}30} 50%{box-shadow:0 0 60px ${ACCENT}60,0 0 100px ${ACCENT}20} }
        .fade-up-1 { animation: fadeUp 0.6s 0.1s ease both; }
        .fade-up-2 { animation: fadeUp 0.6s 0.25s ease both; }
        .fade-up-3 { animation: fadeUp 0.6s 0.4s ease both; }
        .fade-up-4 { animation: fadeUp 0.6s 0.55s ease both; }
        .fade-up-5 { animation: fadeUp 0.6s 0.7s ease both; }
        .cta-primary { display:inline-flex; align-items:center; justify-content:center; gap:10px; padding:16px 28px; background:${ACCENT}; color:#050505; font-family:'Space Mono',monospace; font-weight:700; font-size:12px; letter-spacing:0.1em; text-transform:uppercase; border:none; border-radius:12px; cursor:pointer; transition:all 0.2s; animation:glowPulse 3s ease infinite; min-height:52px; -webkit-tap-highlight-color:transparent; width:100%; }
        .cta-primary:hover { background:#d4ff33; }
        .cta-secondary { display:inline-flex; align-items:center; justify-content:center; gap:8px; padding:15px 24px; background:transparent; color:rgba(255,255,255,0.6); font-family:'Space Mono',monospace; font-size:12px; letter-spacing:0.08em; border:1px solid rgba(255,255,255,0.15); border-radius:12px; cursor:pointer; transition:all 0.2s; min-height:52px; -webkit-tap-highlight-color:transparent; width:100%; }
        .cta-secondary:hover { border-color:rgba(255,255,255,0.35); color:white; }
        .feature-card { background:rgba(255,255,255,0.02); border:1px solid rgba(255,255,255,0.07); border-radius:20px; padding:24px; transition:all 0.3s; position:relative; overflow:hidden; }
        .feature-card:hover { border-color:rgba(255,255,255,0.15); transform:translateY(-4px); }
        .testimonial-card { background:rgba(255,255,255,0.02); border:1px solid rgba(255,255,255,0.07); border-radius:20px; padding:24px; transition:all 0.3s; }
        .testimonial-card:hover { border-color:rgba(255,255,255,0.12); }
        .nav-link { font-family:'Space Mono',monospace; font-size:10px; letter-spacing:0.12em; color:rgba(255,255,255,0.45); background:none; border:none; cursor:pointer; padding:8px 12px; transition:color 0.2s; text-transform:uppercase; min-height:44px; }
        .nav-link:hover { color:white; }
        .tag { display:inline-block; padding:4px 12px; background:rgba(200,255,0,0.08); border:1px solid rgba(200,255,0,0.2); border-radius:4px; font-family:'Space Mono',monospace; font-size:9px; color:${ACCENT}; letter-spacing:0.2em; text-transform:uppercase; }
        .grid-bg { background-image:linear-gradient(rgba(200,255,0,0.03) 1px,transparent 1px),linear-gradient(90deg,rgba(200,255,0,0.03) 1px,transparent 1px); background-size:60px 60px; }
        @media (max-width:768px) {
          .nav-desktop { display: none !important; }
          .hero-section { padding: 100px 20px 60px !important; }
          .section-pad { padding: 60px 20px !important; }
          .feature-grid { grid-template-columns: 1fr !important; }
          .stats-grid { grid-template-columns: 1fr 1fr !important; }
          .steps-grid { grid-template-columns: 1fr !important; gap: 32px !important; }
          .connector-line { display: none !important; }
          .testimonials-grid { grid-template-columns: 1fr !important; }
          .pricing-grid { grid-template-columns: 1fr !important; }
          .cta-primary, .cta-secondary { width: 100% !important; }
          .cta-row { flex-direction: column !important; }
          .footer-inner { flex-direction: column !important; align-items: flex-start !important; gap: 16px !important; }
        }
      `}</style>

      {!isMobile && (
        <div style={{ position: "fixed", pointerEvents: "none", zIndex: 9999, width: 400, height: 400, borderRadius: "50%", background: `radial-gradient(ellipse, rgba(200,255,0,0.04) 0%, transparent 70%)`, transform: `translate(${mousePos.x - 200}px, ${mousePos.y - 200}px)`, transition: "transform 0.1s ease" }} />
      )}
      <div style={{ position: "fixed", top: 0, left: 0, right: 0, height: "2px", background: `linear-gradient(90deg,transparent,rgba(200,255,0,0.2),transparent)`, animation: "scanline 8s linear infinite", pointerEvents: "none", zIndex: 100 }} />

      {/* NAV */}
      <nav style={{ position: "fixed", top: 0, left: 0, right: 0, zIndex: 50, padding: isMobile ? "12px 20px" : "16px 48px", display: "flex", alignItems: "center", justifyContent: "space-between", background: scrollY > 60 ? "rgba(5,5,5,0.92)" : "transparent", backdropFilter: scrollY > 60 ? "blur(20px)" : "none", borderBottom: scrollY > 60 ? "1px solid rgba(255,255,255,0.06)" : "none", transition: "all 0.3s" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
          <div style={{ width: 28, height: 28, borderRadius: "50%", background: ACCENT, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 12 }}>⬡</div>
          <span style={{ fontFamily: "'Syne',sans-serif", fontWeight: 800, fontSize: isMobile ? 16 : 18, color: "white", letterSpacing: "-0.02em" }}>CORTIQ</span>
        </div>
        <div className="nav-desktop" style={{ display: "flex", alignItems: "center", gap: 4 }}>
          {["Features", "How it works", "Pricing"].map(l => <button key={l} className="nav-link">{l}</button>)}
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <button style={{ padding: "9px 16px", background: "transparent", color: "rgba(255,255,255,0.6)", fontFamily: "'Space Mono',monospace", fontSize: 10, letterSpacing: "0.08em", border: "1px solid rgba(255,255,255,0.15)", borderRadius: 10, cursor: "pointer", minHeight: 40, WebkitTapHighlightColor: "transparent" }} onClick={() => router.push("/login")}>Sign in</button>
          {!isMobile && <button style={{ padding: "9px 16px", background: ACCENT, color: "#050505", fontFamily: "'Space Mono',monospace", fontSize: 10, letterSpacing: "0.08em", fontWeight: 700, border: "none", borderRadius: 10, cursor: "pointer", minHeight: 40 }} onClick={() => router.push("/login")}>Get started →</button>}
        </div>
      </nav>

      {/* HERO */}
      <section className="grid-bg hero-section" style={{ minHeight: "100vh", display: "flex", alignItems: "center", padding: isMobile ? "100px 20px 60px" : "100px 48px 80px", position: "relative", overflow: "hidden" }}>
        <div style={{ position: "absolute", top: "20%", left: "60%", width: 400, height: 400, borderRadius: "50%", background: `radial-gradient(ellipse,rgba(200,255,0,0.06) 0%,transparent 70%)`, pointerEvents: "none" }} />
        <div style={{ maxWidth: 1100, margin: "0 auto", width: "100%" }}>
          <div style={{ maxWidth: 720 }}>
            <div className="fade-up-1" style={{ marginBottom: 20 }}><span className="tag">Now in Beta · Free to use</span></div>
            <h1 className="fade-up-2" style={{ fontFamily: "'Syne',sans-serif", fontWeight: 800, fontSize: isMobile ? "clamp(38px,10vw,56px)" : "clamp(44px,6vw,88px)", lineHeight: 1.0, letterSpacing: "-0.03em", marginBottom: 20 }}>
              Startup<br />
              <span style={{ color: ACCENT, fontFamily: "'DM Serif Display',serif", fontStyle: "italic", fontWeight: 400 }}>{ROTATING_WORDS[tick % ROTATING_WORDS.length]}</span><br />
              <span style={{ color: "rgba(255,255,255,0.25)" }}>for Founders</span>
            </h1>
            <p className="fade-up-3" style={{ fontFamily: "'Space Mono',monospace", fontSize: isMobile ? 11 : 13, lineHeight: 1.9, color: "rgba(255,255,255,0.45)", maxWidth: 540, marginBottom: 32 }}>
              Cortiq analyzes your startup across 5 dimensions in seconds. Health scores, OKRs, pitch decks, burn modeling, competitor intel — everything a serious founder needs.
            </p>
            <div className="fade-up-4 cta-row" style={{ display: "flex", alignItems: "center", gap: 12 }}>
              <button className="cta-primary" style={{ width: isMobile ? "100%" : "auto" }} onClick={() => router.push("/login")}>⬡ Analyze my startup</button>
              <button className="cta-secondary" style={{ width: isMobile ? "100%" : "auto" }} onClick={() => router.push("/login")}>See a demo →</button>
            </div>
            <div className="fade-up-5" style={{ marginTop: 36, display: "flex", alignItems: "center", gap: 14 }}>
              <div style={{ display: "flex" }}>
                {["A", "P", "D", "R", "K"].map((l, i) => <div key={i} style={{ width: 28, height: 28, borderRadius: "50%", background: `hsl(${i * 60},60%,50%)`, border: "2px solid #050505", marginLeft: i === 0 ? 0 : -7, display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "'Space Mono',monospace", fontSize: 9, color: "white" }}>{l}</div>)}
              </div>
              <span style={{ fontFamily: "'Space Mono',monospace", fontSize: 10, color: "rgba(255,255,255,0.3)" }}>Joined by 200+ founders this week</span>
            </div>
          </div>
        </div>
      </section>

      {/* STATS */}
      <section style={{ borderTop: "1px solid rgba(255,255,255,0.06)", borderBottom: "1px solid rgba(255,255,255,0.06)" }}>
        <div style={{ maxWidth: 1100, margin: "0 auto", padding: isMobile ? "0 20px" : "0 48px", display: "grid", gridTemplateColumns: isMobile ? "1fr 1fr" : "repeat(4,1fr)" }} className="stats-grid">
          {STATS.map((s, i) => (
            <div key={s.label} style={{ textAlign: "center", padding: isMobile ? "24px 12px" : "32px 24px", borderRight: i < STATS.length - 1 && (!isMobile || i % 2 === 0) ? "1px solid rgba(255,255,255,0.06)" : "none", borderBottom: isMobile && i < 2 ? "1px solid rgba(255,255,255,0.06)" : "none" }}>
              <div style={{ fontFamily: "'Syne',sans-serif", fontWeight: 800, fontSize: isMobile ? 32 : 40, color: ACCENT, lineHeight: 1, marginBottom: 6 }}>{s.value}</div>
              <div style={{ fontFamily: "'Space Mono',monospace", fontSize: 8, color: "rgba(255,255,255,0.3)", letterSpacing: "0.12em", textTransform: "uppercase" }}>{s.label}</div>
            </div>
          ))}
        </div>
      </section>

      {/* FEATURES */}
      <section className="section-pad" style={{ padding: isMobile ? "60px 20px" : "100px 48px", maxWidth: 1100, margin: "0 auto" }}>
        <div style={{ textAlign: "center", marginBottom: isMobile ? 40 : 64 }}>
          <span className="tag" style={{ marginBottom: 16, display: "inline-block" }}>Everything you need</span>
          <h2 style={{ fontFamily: "'Syne',sans-serif", fontWeight: 800, fontSize: isMobile ? "clamp(26px,7vw,40px)" : "clamp(32px,4vw,56px)", letterSpacing: "-0.02em", lineHeight: 1.1 }}>
            Built for founders who<br /><span style={{ color: ACCENT, fontFamily: "'DM Serif Display',serif", fontStyle: "italic", fontWeight: 400 }}>measure everything</span>
          </h2>
        </div>
        <div className="feature-grid" style={{ display: "grid", gridTemplateColumns: isMobile ? "1fr" : "repeat(3,1fr)", gap: 14 }}>
          {FEATURES.map((f, i) => (
            <div key={f.title} className="feature-card" style={{ "--card-color": f.color } as any}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 16 }}>
                <div style={{ width: 40, height: 40, borderRadius: 12, background: `${f.color}15`, border: `1px solid ${f.color}30`, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 16 }}>{f.icon}</div>
                <span style={{ fontFamily: "'Space Mono',monospace", fontSize: 8, color: f.color, background: `${f.color}10`, border: `1px solid ${f.color}20`, borderRadius: 4, padding: "3px 8px", letterSpacing: "0.1em" }}>{f.stat}</span>
              </div>
              <h3 style={{ fontFamily: "'Syne',sans-serif", fontWeight: 700, fontSize: 17, color: "white", marginBottom: 8 }}>{f.title}</h3>
              <p style={{ fontFamily: "'Space Mono',monospace", fontSize: 10, lineHeight: 1.8, color: "rgba(255,255,255,0.4)" }}>{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* HOW IT WORKS */}
      <section style={{ padding: isMobile ? "60px 20px" : "100px 48px", background: "rgba(255,255,255,0.01)", borderTop: "1px solid rgba(255,255,255,0.05)", borderBottom: "1px solid rgba(255,255,255,0.05)" }}>
        <div style={{ maxWidth: 1100, margin: "0 auto" }}>
          <div style={{ textAlign: "center", marginBottom: isMobile ? 40 : 64 }}>
            <span className="tag" style={{ marginBottom: 16, display: "inline-block" }}>How it works</span>
            <h2 style={{ fontFamily: "'Syne',sans-serif", fontWeight: 800, fontSize: isMobile ? "clamp(24px,7vw,40px)" : "clamp(32px,4vw,52px)", letterSpacing: "-0.02em" }}>
              From zero to clarity<br /><span style={{ color: ACCENT }}>in 60 seconds</span>
            </h2>
          </div>
          <div className="steps-grid" style={{ display: "grid", gridTemplateColumns: isMobile ? "1fr" : "repeat(3,1fr)", gap: 0, position: "relative" }}>
            {!isMobile && <div className="connector-line" style={{ position: "absolute", top: 32, left: "16%", right: "16%", height: 1, background: `linear-gradient(90deg,${ACCENT}40,${CYAN}40)`, zIndex: 0 }} />}
            {[
              { step: "01", title: "Fill in your details", desc: "Startup idea, team size, revenue, burn rate, market size. Takes 2 minutes.", icon: "◈", color: ACCENT },
              { step: "02", title: "AI runs the analysis", desc: "Our engine scores 5 dimensions and generates insights, strategy, and roadmap.", icon: "⬡", color: CYAN },
              { step: "03", title: "Act on your results", desc: "Use the OKR generator, pitch deck, simulator, and competitor intel to move fast.", icon: "★", color: PURPLE },
            ].map((s) => (
              <div key={s.step} style={{ textAlign: "center", padding: isMobile ? "0 0 24px" : "0 32px", position: "relative", zIndex: 1 }}>
                <div style={{ width: 56, height: 56, borderRadius: "50%", background: "#050505", border: `2px solid ${s.color}`, display: "flex", alignItems: "center", justifyContent: "center", margin: "0 auto 20px", fontSize: 20, boxShadow: `0 0 20px ${s.color}30` }}>{s.icon}</div>
                <div style={{ fontFamily: "'Space Mono',monospace", fontSize: 9, color: s.color, letterSpacing: "0.2em", marginBottom: 10 }}>STEP {s.step}</div>
                <h3 style={{ fontFamily: "'Syne',sans-serif", fontWeight: 700, fontSize: 18, marginBottom: 10 }}>{s.title}</h3>
                <p style={{ fontFamily: "'Space Mono',monospace", fontSize: 10, lineHeight: 1.8, color: "rgba(255,255,255,0.4)" }}>{s.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* TESTIMONIALS */}
      <section style={{ padding: isMobile ? "60px 20px" : "100px 48px" }}>
        <div style={{ maxWidth: 1100, margin: "0 auto" }}>
          <div style={{ textAlign: "center", marginBottom: isMobile ? 32 : 56 }}>
            <span className="tag" style={{ marginBottom: 16, display: "inline-block" }}>Founder stories</span>
            <h2 style={{ fontFamily: "'Syne',sans-serif", fontWeight: 800, fontSize: isMobile ? "clamp(22px,6vw,38px)" : "clamp(28px,3.5vw,48px)", letterSpacing: "-0.02em" }}>
              Founders who <span style={{ color: ACCENT, fontFamily: "'DM Serif Display',serif", fontStyle: "italic", fontWeight: 400 }}>ship faster</span>
            </h2>
          </div>
          <div className="testimonials-grid" style={{ display: "grid", gridTemplateColumns: isMobile ? "1fr" : "repeat(3,1fr)", gap: 14 }}>
            {TESTIMONIALS.map(t => (
              <div key={t.name} className="testimonial-card">
                <div style={{ fontSize: 24, color: t.color, marginBottom: 12, opacity: 0.6 }}>"</div>
                <p style={{ fontFamily: "'DM Serif Display',serif", fontSize: isMobile ? 15 : 17, lineHeight: 1.6, color: "rgba(255,255,255,0.85)", marginBottom: 20, fontStyle: "italic" }}>{t.quote}</p>
                <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                  <div style={{ width: 34, height: 34, borderRadius: "50%", background: `${t.color}20`, border: `1px solid ${t.color}40`, display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "'Space Mono',monospace", fontSize: 11, color: t.color }}>{t.avatar}</div>
                  <div>
                    <div style={{ fontFamily: "'Syne',sans-serif", fontWeight: 700, fontSize: 13, color: "white" }}>{t.name}</div>
                    <div style={{ fontFamily: "'Space Mono',monospace", fontSize: 9, color: "rgba(255,255,255,0.3)" }}>{t.role}</div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* PRICING */}
      <section style={{ padding: isMobile ? "60px 20px" : "100px 48px", background: "rgba(255,255,255,0.01)", borderTop: "1px solid rgba(255,255,255,0.05)" }}>
        <div style={{ maxWidth: 800, margin: "0 auto", textAlign: "center" }}>
          <span className="tag" style={{ marginBottom: 16, display: "inline-block" }}>Pricing</span>
          <h2 style={{ fontFamily: "'Syne',sans-serif", fontWeight: 800, fontSize: isMobile ? "clamp(24px,7vw,40px)" : "clamp(32px,4vw,52px)", letterSpacing: "-0.02em", marginBottom: 12 }}>
            Free while in beta.<br /><span style={{ color: ACCENT }}>Always founder-first.</span>
          </h2>
          <p style={{ fontFamily: "'Space Mono',monospace", fontSize: 11, color: "rgba(255,255,255,0.35)", lineHeight: 1.8, marginBottom: 48, maxWidth: 500, margin: "0 auto 48px" }}>
            Full access to every feature during beta. No credit card. No limits.
          </p>
          <div className="pricing-grid" style={{ display: "grid", gridTemplateColumns: isMobile ? "1fr" : "1fr 1fr", gap: 14, maxWidth: 680, margin: "0 auto" }}>
            {[
              { name: "Free", price: "$0", period: "forever", features: ["Unlimited analyses", "Health scoring", "Burn simulator", "OKR generator", "Progress tracking"], cta: "Start for free", accent: false },
              { name: "Pro", price: "$29", period: "/ month", features: ["Everything in Free", "PDF export", "Pitch deck generator", "Competitor deep-dive", "Priority AI responses"], cta: "Coming soon", accent: true },
            ].map(plan => (
              <div key={plan.name} style={{ background: plan.accent ? `${ACCENT}08` : "rgba(255,255,255,0.02)", border: `1px solid ${plan.accent ? ACCENT + "30" : "rgba(255,255,255,0.08)"}`, borderRadius: 20, padding: "32px 28px", textAlign: "left" }}>
                <div style={{ fontFamily: "'Space Mono',monospace", fontSize: 9, color: plan.accent ? ACCENT : "rgba(255,255,255,0.3)", letterSpacing: "0.2em", textTransform: "uppercase", marginBottom: 14 }}>{plan.name}</div>
                <div style={{ display: "flex", alignItems: "baseline", gap: 6, marginBottom: 20 }}>
                  <span style={{ fontFamily: "'Syne',sans-serif", fontWeight: 800, fontSize: 40, color: "white" }}>{plan.price}</span>
                  <span style={{ fontFamily: "'Space Mono',monospace", fontSize: 11, color: "rgba(255,255,255,0.3)" }}>{plan.period}</span>
                </div>
                <div style={{ height: 1, background: "rgba(255,255,255,0.06)", marginBottom: 20 }} />
                <div style={{ display: "flex", flexDirection: "column", gap: 10, marginBottom: 24 }}>
                  {plan.features.map(f => (
                    <div key={f} style={{ display: "flex", alignItems: "center", gap: 10 }}>
                      <span style={{ color: plan.accent ? ACCENT : "rgba(255,255,255,0.3)", fontSize: 11 }}>✓</span>
                      <span style={{ fontFamily: "'Space Mono',monospace", fontSize: 10, color: "rgba(255,255,255,0.55)" }}>{f}</span>
                    </div>
                  ))}
                </div>
                <button onClick={() => !plan.accent && router.push("/login")} style={{ width: "100%", padding: "14px", fontFamily: "'Space Mono',monospace", fontSize: 11, fontWeight: 700, letterSpacing: "0.1em", background: plan.accent ? "rgba(200,255,0,0.1)" : ACCENT, color: plan.accent ? ACCENT : "#050505", border: plan.accent ? `1px solid ${ACCENT}30` : "none", borderRadius: 10, cursor: plan.accent ? "default" : "pointer", opacity: plan.accent ? 0.7 : 1, minHeight: 52, WebkitTapHighlightColor: "transparent" }}>
                  {plan.cta} {!plan.accent && "→"}
                </button>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="grid-bg" style={{ padding: isMobile ? "80px 20px" : "120px 48px", textAlign: "center", position: "relative", overflow: "hidden" }}>
        <div style={{ position: "absolute", top: "50%", left: "50%", transform: "translate(-50%,-50%)", width: 600, height: 300, background: `radial-gradient(ellipse,rgba(200,255,0,0.06) 0%,transparent 70%)`, pointerEvents: "none" }} />
        <div style={{ position: "relative", zIndex: 1 }}>
          <span className="tag" style={{ marginBottom: 20, display: "inline-block" }}>Get started today</span>
          <h2 style={{ fontFamily: "'Syne',sans-serif", fontWeight: 800, fontSize: isMobile ? "clamp(32px,9vw,56px)" : "clamp(36px,5vw,72px)", letterSpacing: "-0.03em", lineHeight: 1.05, marginBottom: 20 }}>
            Stop guessing.<br /><span style={{ color: ACCENT, fontFamily: "'DM Serif Display',serif", fontStyle: "italic", fontWeight: 400 }}>Start knowing.</span>
          </h2>
          <p style={{ fontFamily: "'Space Mono',monospace", fontSize: 12, color: "rgba(255,255,255,0.35)", marginBottom: 40, maxWidth: 360, margin: "0 auto 40px", lineHeight: 1.8 }}>
            Your startup health score is waiting. Free to use. No credit card. Results in 60 seconds.
          </p>
          <button className="cta-primary" style={{ fontSize: 13, padding: "18px 36px", width: isMobile ? "100%" : "auto", animation: "glowPulse 3s ease infinite" }} onClick={() => router.push("/login")}>
            ⬡ Analyze my startup for free
          </button>
        </div>
      </section>

      {/* FOOTER */}
      <footer style={{ borderTop: "1px solid rgba(255,255,255,0.06)", padding: isMobile ? "28px 20px" : "36px 48px" }}>
        <div className="footer-inner" style={{ display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: 14 }}>
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <div style={{ width: 22, height: 22, borderRadius: "50%", background: ACCENT, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 9 }}>⬡</div>
            <span style={{ fontFamily: "'Syne',sans-serif", fontWeight: 800, fontSize: 14, color: "white" }}>CORTIQ</span>
          </div>
          <span style={{ fontFamily: "'Space Mono',monospace", fontSize: 9, color: "rgba(255,255,255,0.2)", letterSpacing: "0.1em" }}>© 2025 CORTIQ · AI STARTUP INTELLIGENCE</span>
          <div style={{ display: "flex", gap: 16 }}>
            {["Privacy", "Terms", "Contact"].map(l => (
              <button key={l} style={{ fontFamily: "'Space Mono',monospace", fontSize: 9, color: "rgba(255,255,255,0.25)", background: "none", border: "none", cursor: "pointer", letterSpacing: "0.1em", minHeight: 40 }}>{l}</button>
            ))}
          </div>
        </div>
      </footer>
    </>
  );
}