"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";

const ACCENT = "#C8FF00";
const CYAN   = "#00E5FF";
const PURPLE = "#A855F7";

const FEATURES = [
  {
    icon: "⬡",
    title: "Health Diagnostics",
    desc: "Deep 5-dimension analysis across market, execution, finance, growth, and competition. Know exactly where you stand.",
    color: ACCENT,
    stat: "5 dimensions",
  },
  {
    icon: "◎",
    title: "Burn Rate Simulator",
    desc: "Model your runway in real-time. Compare scenarios A vs B and find the burn rate that gets you to Series A.",
    color: CYAN,
    stat: "36-month model",
  },
  {
    icon: "★",
    title: "Pitch Deck AI",
    desc: "Generate a full investor-ready pitch deck in seconds. Tailored tone for investors, customers, or partners.",
    color: "#FFB800",
    stat: "10 slides, 3 tones",
  },
  {
    icon: "⊕",
    title: "Competitor Intel",
    desc: "Deep-dive on any competitor. Threat scores, radar charts, your edge — all generated by AI from real data.",
    color: PURPLE,
    stat: "6-axis analysis",
  },
  {
    icon: "◈",
    title: "OKR Engine",
    desc: "Auto-generate a full year of OKRs tailored to your stage, team size, and health scores.",
    color: "#FF6B35",
    stat: "4 quarters, 12 KRs",
  },
  {
    icon: "🔥",
    title: "Progress Tracker",
    desc: "Weekly check-in streaks, score history, achievements. Build the habit of measuring what matters.",
    color: "#FF6B35",
    stat: "10 achievements",
  },
];

const STATS = [
  { value: "5",    label: "Analysis Dimensions"  },
  { value: "10+",  label: "AI-Powered Features"  },
  { value: "36mo", label: "Runway Modeling"       },
  { value: "∞",    label: "Scenarios to Explore" },
];

const TESTIMONIALS = [
  {
    quote: "Cortiq told us our execution score was 34. We fixed our hiring plan and raised our seed in 6 weeks.",
    name: "Arjun M.",
    role: "Founder, DevFlow",
    avatar: "A",
    color: ACCENT,
  },
  {
    quote: "The OKR generator alone saved us 3 planning sessions. It just knows what a Series A startup needs.",
    name: "Priya K.",
    role: "CEO, NestScale",
    avatar: "P",
    color: CYAN,
  },
  {
    quote: "I run an analysis every Monday. My health score went from 41 to 78 in 3 months.",
    name: "Dani R.",
    role: "Co-founder, Loopstack",
    avatar: "D",
    color: PURPLE,
  },
];

export default function LandingPage() {
  const router       = useRouter();
  const heroRef      = useRef<HTMLDivElement>(null);
  const [tick, setTick]       = useState(0);
  const [mousePos, setMousePos] = useState({ x: 0, y: 0 });
  const [scrollY, setScrollY]   = useState(0);

  useEffect(() => {
    const interval = setInterval(() => setTick(t => t + 1), 2000);
    return () => clearInterval(interval);
  }, []);

  useEffect(() => {
    const handleMouse = (e: MouseEvent) => setMousePos({ x: e.clientX, y: e.clientY });
    const handleScroll = () => setScrollY(window.scrollY);
    window.addEventListener("mousemove", handleMouse);
    window.addEventListener("scroll", handleScroll);
    return () => { window.removeEventListener("mousemove", handleMouse); window.removeEventListener("scroll", handleScroll); };
  }, []);

  const ROTATING_WORDS = ["Intelligence", "Diagnostics", "Clarity", "Advantage", "Readiness"];
  const currentWord = ROTATING_WORDS[tick % ROTATING_WORDS.words];

  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Space+Mono:ital,wght@0,400;0,700;1,400&family=Syne:wght@700;800&family=DM+Serif+Display:ital@0;1&display=swap');

        *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
        html { scroll-behavior: smooth; }
        body { background: #050505; color: white; overflow-x: hidden; }
        ::-webkit-scrollbar { width: 3px; }
        ::-webkit-scrollbar-thumb { background: #1a1a1a; }

        @keyframes fadeUp    { from{opacity:0;transform:translateY(24px)} to{opacity:1;transform:translateY(0)} }
        @keyframes fadeIn    { from{opacity:0} to{opacity:1} }
        @keyframes scanline  { 0%{transform:translateY(-100%)} 100%{transform:translateY(100vh)} }
        @keyframes spin      { to{transform:rotate(360deg)} }
        @keyframes pulse     { 0%,100%{opacity:1} 50%{opacity:0.4} }
        @keyframes float     { 0%,100%{transform:translateY(0)} 50%{transform:translateY(-12px)} }
        @keyframes wordSwap  { 0%{opacity:0;transform:translateY(10px)} 15%,85%{opacity:1;transform:translateY(0)} 100%{opacity:0;transform:translateY(-10px)} }
        @keyframes dash      { to{stroke-dashoffset:0} }
        @keyframes glowPulse { 0%,100%{box-shadow:0 0 20px ${ACCENT}30} 50%{box-shadow:0 0 60px ${ACCENT}60,0 0 100px ${ACCENT}20} }

        .fade-up-1 { animation: fadeUp 0.6s 0.1s ease both; }
        .fade-up-2 { animation: fadeUp 0.6s 0.25s ease both; }
        .fade-up-3 { animation: fadeUp 0.6s 0.4s ease both; }
        .fade-up-4 { animation: fadeUp 0.6s 0.55s ease both; }
        .fade-up-5 { animation: fadeUp 0.6s 0.7s ease both; }

        .word-rotate { display:inline-block; animation: wordSwap 2s ease both; }

        .cta-primary {
          display: inline-flex; align-items: center; gap: 10px;
          padding: 16px 32px; background: ${ACCENT}; color: #050505;
          font-family: 'Space Mono', monospace; font-weight: 700;
          font-size: 13px; letter-spacing: 0.1em; text-transform: uppercase;
          border: none; border-radius: 12px; cursor: pointer;
          transition: all 0.2s; animation: glowPulse 3s ease infinite;
        }
        .cta-primary:hover { background: #d4ff33; transform: translateY(-2px) scale(1.02); }

        .cta-secondary {
          display: inline-flex; align-items: center; gap: 8px;
          padding: 16px 28px; background: transparent; color: rgba(255,255,255,0.6);
          font-family: 'Space Mono', monospace; font-size: 12px; letter-spacing: 0.08em;
          border: 1px solid rgba(255,255,255,0.15); border-radius: 12px; cursor: pointer;
          transition: all 0.2s;
        }
        .cta-secondary:hover { border-color: rgba(255,255,255,0.35); color: white; }

        .feature-card {
          background: rgba(255,255,255,0.02);
          border: 1px solid rgba(255,255,255,0.07);
          border-radius: 20px; padding: 32px;
          transition: all 0.3s; cursor: default; position: relative; overflow: hidden;
        }
        .feature-card::before {
          content: ''; position: absolute; inset: 0;
          background: var(--card-color, ${ACCENT});
          opacity: 0; transition: opacity 0.3s;
        }
        .feature-card:hover { border-color: rgba(255,255,255,0.15); transform: translateY(-4px); }
        .feature-card:hover::before { opacity: 0.04; }

        .testimonial-card {
          background: rgba(255,255,255,0.02);
          border: 1px solid rgba(255,255,255,0.07);
          border-radius: 20px; padding: 28px 32px;
          transition: all 0.3s;
        }
        .testimonial-card:hover { border-color: rgba(255,255,255,0.12); transform: translateY(-3px); }

        .nav-link {
          font-family: 'Space Mono', monospace; font-size: 10px;
          letter-spacing: 0.12em; color: rgba(255,255,255,0.45);
          background: none; border: none; cursor: pointer;
          padding: 6px 12px; transition: color 0.2s;
          text-transform: uppercase;
        }
        .nav-link:hover { color: white; }

        .stat-card {
          text-align: center; padding: 32px 24px;
          border-right: 1px solid rgba(255,255,255,0.06);
        }
        .stat-card:last-child { border-right: none; }

        .tag {
          display: inline-block; padding: 4px 12px;
          background: rgba(200,255,0,0.08);
          border: 1px solid rgba(200,255,0,0.2);
          border-radius: 4px; font-family: 'Space Mono', monospace;
          font-size: 9px; color: ${ACCENT}; letter-spacing: 0.2em;
          text-transform: uppercase;
        }

        .grid-bg {
          background-image: linear-gradient(rgba(200,255,0,0.03) 1px, transparent 1px),
                            linear-gradient(90deg, rgba(200,255,0,0.03) 1px, transparent 1px);
          background-size: 60px 60px;
        }

        section { position: relative; }
      `}</style>

      {/* cursor glow */}
      <div style={{
        position: "fixed", pointerEvents: "none", zIndex: 9999,
        width: 400, height: 400, borderRadius: "50%",
        background: `radial-gradient(ellipse, rgba(200,255,0,0.04) 0%, transparent 70%)`,
        transform: `translate(${mousePos.x - 200}px, ${mousePos.y - 200}px)`,
        transition: "transform 0.1s ease",
      }} />

      {/* scanline */}
      <div style={{ position:"fixed", top:0, left:0, right:0, height:"2px", background:`linear-gradient(90deg,transparent,rgba(200,255,0,0.2),transparent)`, animation:"scanline 8s linear infinite", pointerEvents:"none", zIndex:100 }} />

      {/* ── NAV ────────────────────────────────────────────────────────── */}
      <nav style={{
        position: "fixed", top: 0, left: 0, right: 0, zIndex: 50,
        padding: "16px 48px", display: "flex", alignItems: "center", justifyContent: "space-between",
        background: scrollY > 60 ? "rgba(5,5,5,0.92)" : "transparent",
        backdropFilter: scrollY > 60 ? "blur(20px)" : "none",
        borderBottom: scrollY > 60 ? "1px solid rgba(255,255,255,0.06)" : "none",
        transition: "all 0.3s",
      }}>
        <div style={{ display:"flex", alignItems:"center", gap:10 }}>
          <div style={{ width:32, height:32, borderRadius:"50%", background:ACCENT, display:"flex", alignItems:"center", justifyContent:"center", fontSize:14 }}>⬡</div>
          <span style={{ fontFamily:"'Syne',sans-serif", fontWeight:800, fontSize:18, color:"white", letterSpacing:"-0.02em" }}>CORTIQ</span>
        </div>
        <div style={{ display:"flex", alignItems:"center", gap:4 }}>
          {["Features", "How it works", "Pricing"].map(l => (
            <button key={l} className="nav-link">{l}</button>
          ))}
        </div>
        <div style={{ display:"flex", alignItems:"center", gap:10 }}>
          <button className="cta-secondary" style={{ padding:"9px 20px", fontSize:11 }} onClick={() => router.push("/login")}>Sign in</button>
          <button className="cta-primary" style={{ padding:"10px 20px", fontSize:11 }} onClick={() => router.push("/login")}>Get started free →</button>
        </div>
      </nav>

      {/* ── HERO ───────────────────────────────────────────────────────── */}
      <section className="grid-bg" style={{ minHeight:"100vh", display:"flex", alignItems:"center", paddingTop:100, paddingBottom:80, position:"relative", overflow:"hidden" }}>

        {/* ambient orbs */}
        <div style={{ position:"absolute", top:"20%", left:"60%", width:600, height:600, borderRadius:"50%", background:`radial-gradient(ellipse,rgba(200,255,0,0.06) 0%,transparent 70%)`, pointerEvents:"none" }} />
        <div style={{ position:"absolute", top:"50%", left:"10%", width:400, height:400, borderRadius:"50%", background:`radial-gradient(ellipse,rgba(0,229,255,0.04) 0%,transparent 70%)`, pointerEvents:"none" }} />

        <div style={{ maxWidth:1100, margin:"0 auto", padding:"0 48px", width:"100%" }}>
          <div style={{ maxWidth:820 }}>

            <div className="fade-up-1" style={{ marginBottom:24 }}>
              <span className="tag">Now in Beta · Free to use</span>
            </div>

            <h1 className="fade-up-2" style={{ fontFamily:"'Syne',sans-serif", fontWeight:800, fontSize:"clamp(44px,6vw,88px)", lineHeight:1.0, letterSpacing:"-0.03em", marginBottom:24 }}>
              Startup
              <br />
              <span style={{ color:ACCENT, fontFamily:"'DM Serif Display',serif", fontStyle:"italic", fontWeight:400 }}>
                {ROTATING_WORDS[tick % ROTATING_WORDS.length]}
              </span>
              <br />
              <span style={{ color:"rgba(255,255,255,0.25)" }}>for Founders</span>
            </h1>

            <p className="fade-up-3" style={{ fontFamily:"'Space Mono',monospace", fontSize:13, lineHeight:1.9, color:"rgba(255,255,255,0.45)", maxWidth:560, marginBottom:40 }}>
              Cortiq analyzes your startup across 5 dimensions in seconds.
              Health scores, OKRs, pitch decks, burn modeling, competitor intel —
              everything a serious founder needs.
            </p>

            <div className="fade-up-4" style={{ display:"flex", alignItems:"center", gap:16, flexWrap:"wrap" }}>
              <button className="cta-primary" onClick={() => router.push("/login")}>
                ⬡ Analyze my startup
              </button>
              <button className="cta-secondary" onClick={() => router.push("/login")}>
                See a demo →
              </button>
            </div>

            <div className="fade-up-5" style={{ marginTop:48, display:"flex", alignItems:"center", gap:20 }}>
              <div style={{ display:"flex" }}>
                {["A","P","D","R","K"].map((l,i) => (
                  <div key={i} style={{ width:30, height:30, borderRadius:"50%", background:`hsl(${i*60},60%,50%)`, border:"2px solid #050505", marginLeft: i === 0 ? 0 : -8, display:"flex", alignItems:"center", justifyContent:"center", fontFamily:"'Space Mono',monospace", fontSize:10, color:"white" }}>{l}</div>
                ))}
              </div>
              <span style={{ fontFamily:"'Space Mono',monospace", fontSize:10, color:"rgba(255,255,255,0.3)" }}>
                Joined by 200+ founders this week
              </span>
            </div>
          </div>
        </div>

        {/* floating score card */}
        <div style={{
          position:"absolute", right:48, top:"50%", transform:`translateY(-50%) translateY(${Math.sin(Date.now()/2000)*8}px)`,
          animation:"float 4s ease-in-out infinite",
          background:"rgba(10,10,10,0.95)", border:"1px solid rgba(200,255,0,0.2)",
          borderRadius:20, padding:"28px 32px", width:260,
          boxShadow:`0 0 40px rgba(200,255,0,0.1), 0 24px 64px rgba(0,0,0,0.5)`,
          display:"none",
        }}
          className="floating-card"
        >
          <div style={{ fontFamily:"'Space Mono',monospace", fontSize:8, color:"rgba(255,255,255,0.3)", letterSpacing:"0.2em", textTransform:"uppercase", marginBottom:16 }}>Live Analysis</div>
          <div style={{ fontFamily:"'Syne',sans-serif", fontWeight:800, fontSize:48, color:ACCENT, lineHeight:1 }}>74</div>
          <div style={{ fontFamily:"'Space Mono',monospace", fontSize:10, color:"rgba(255,255,255,0.4)", marginBottom:20 }}>Health Score</div>
          {[["Market","82",ACCENT],["Execution","61","#FFB800"],["Finance","78",CYAN],["Growth","71",PURPLE]].map(([l,v,c]) => (
            <div key={l} style={{ display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:8 }}>
              <span style={{ fontFamily:"'Space Mono',monospace", fontSize:9, color:"rgba(255,255,255,0.35)" }}>{l}</span>
              <div style={{ display:"flex", alignItems:"center", gap:8 }}>
                <div style={{ width:60, height:3, background:"rgba(255,255,255,0.06)", borderRadius:2 }}>
                  <div style={{ height:"100%", width:`${v}%`, background:c as string, borderRadius:2 }} />
                </div>
                <span style={{ fontFamily:"'Space Mono',monospace", fontSize:9, color:c as string, width:20, textAlign:"right" }}>{v}</span>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ── STATS BAR ──────────────────────────────────────────────────── */}
      <section style={{ borderTop:"1px solid rgba(255,255,255,0.06)", borderBottom:"1px solid rgba(255,255,255,0.06)" }}>
        <div style={{ maxWidth:1100, margin:"0 auto", padding:"0 48px", display:"grid", gridTemplateColumns:"repeat(4,1fr)" }}>
          {STATS.map(s => (
            <div key={s.label} className="stat-card">
              <div style={{ fontFamily:"'Syne',sans-serif", fontWeight:800, fontSize:40, color:ACCENT, lineHeight:1, marginBottom:8 }}>{s.value}</div>
              <div style={{ fontFamily:"'Space Mono',monospace", fontSize:9, color:"rgba(255,255,255,0.3)", letterSpacing:"0.15em", textTransform:"uppercase" }}>{s.label}</div>
            </div>
          ))}
        </div>
      </section>

      {/* ── FEATURES ───────────────────────────────────────────────────── */}
      <section style={{ padding:"120px 48px", maxWidth:1100, margin:"0 auto" }}>
        <div style={{ textAlign:"center", marginBottom:72 }}>
          <span className="tag" style={{ marginBottom:20, display:"inline-block" }}>Everything you need</span>
          <h2 style={{ fontFamily:"'Syne',sans-serif", fontWeight:800, fontSize:"clamp(32px,4vw,56px)", letterSpacing:"-0.02em", lineHeight:1.1 }}>
            Built for founders who<br />
            <span style={{ color:ACCENT, fontFamily:"'DM Serif Display',serif", fontStyle:"italic", fontWeight:400 }}>measure everything</span>
          </h2>
        </div>

        <div style={{ display:"grid", gridTemplateColumns:"repeat(3,1fr)", gap:16 }}>
          {FEATURES.map((f, i) => (
            <div key={f.title} className="feature-card" style={{ "--card-color": f.color, animationDelay:`${i*0.08}s` } as any}>
              <div style={{ display:"flex", justifyContent:"space-between", alignItems:"flex-start", marginBottom:20 }}>
                <div style={{ width:44, height:44, borderRadius:12, background:`${f.color}15`, border:`1px solid ${f.color}30`, display:"flex", alignItems:"center", justifyContent:"center", fontSize:18 }}>{f.icon}</div>
                <span style={{ fontFamily:"'Space Mono',monospace", fontSize:8, color:f.color, background:`${f.color}10`, border:`1px solid ${f.color}20`, borderRadius:4, padding:"3px 8px", letterSpacing:"0.1em" }}>{f.stat}</span>
              </div>
              <h3 style={{ fontFamily:"'Syne',sans-serif", fontWeight:700, fontSize:18, color:"white", marginBottom:10 }}>{f.title}</h3>
              <p style={{ fontFamily:"'Space Mono',monospace", fontSize:10, lineHeight:1.8, color:"rgba(255,255,255,0.4)" }}>{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── HOW IT WORKS ───────────────────────────────────────────────── */}
      <section style={{ padding:"120px 48px", background:"rgba(255,255,255,0.01)", borderTop:"1px solid rgba(255,255,255,0.05)", borderBottom:"1px solid rgba(255,255,255,0.05)" }}>
        <div style={{ maxWidth:1100, margin:"0 auto" }}>
          <div style={{ textAlign:"center", marginBottom:72 }}>
            <span className="tag" style={{ marginBottom:20, display:"inline-block" }}>How it works</span>
            <h2 style={{ fontFamily:"'Syne',sans-serif", fontWeight:800, fontSize:"clamp(32px,4vw,52px)", letterSpacing:"-0.02em" }}>
              From zero to clarity<br />
              <span style={{ color:ACCENT }}>in 60 seconds</span>
            </h2>
          </div>

          <div style={{ display:"grid", gridTemplateColumns:"repeat(3,1fr)", gap:0, position:"relative" }}>
            {/* connector line */}
            <div style={{ position:"absolute", top:32, left:"16%", right:"16%", height:1, background:`linear-gradient(90deg,${ACCENT}40,${CYAN}40)`, zIndex:0 }} />

            {[
              { step:"01", title:"Fill in your details", desc:"Startup idea, team size, revenue, burn rate, market size. Takes 2 minutes.", icon:"◈", color:ACCENT },
              { step:"02", title:"AI runs the analysis", desc:"Our engine scores 5 dimensions and generates insights, strategy, and roadmap.", icon:"⬡", color:CYAN },
              { step:"03", title:"Act on your results", desc:"Use the OKR generator, pitch deck, simulator, and competitor intel to move fast.", icon:"★", color:PURPLE },
            ].map((s, i) => (
              <div key={s.step} style={{ textAlign:"center", padding:"0 32px", position:"relative", zIndex:1 }}>
                <div style={{ width:64, height:64, borderRadius:"50%", background:"#050505", border:`2px solid ${s.color}`, display:"flex", alignItems:"center", justifyContent:"center", margin:"0 auto 24px", fontSize:22, boxShadow:`0 0 20px ${s.color}30` }}>{s.icon}</div>
                <div style={{ fontFamily:"'Space Mono',monospace", fontSize:9, color:s.color, letterSpacing:"0.2em", marginBottom:12 }}>STEP {s.step}</div>
                <h3 style={{ fontFamily:"'Syne',sans-serif", fontWeight:700, fontSize:20, marginBottom:12 }}>{s.title}</h3>
                <p style={{ fontFamily:"'Space Mono',monospace", fontSize:10, lineHeight:1.8, color:"rgba(255,255,255,0.4)" }}>{s.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── TESTIMONIALS ───────────────────────────────────────────────── */}
      <section style={{ padding:"120px 48px" }}>
        <div style={{ maxWidth:1100, margin:"0 auto" }}>
          <div style={{ textAlign:"center", marginBottom:64 }}>
            <span className="tag" style={{ marginBottom:20, display:"inline-block" }}>Founder stories</span>
            <h2 style={{ fontFamily:"'Syne',sans-serif", fontWeight:800, fontSize:"clamp(28px,3.5vw,48px)", letterSpacing:"-0.02em" }}>
              Founders who <span style={{ color:ACCENT, fontFamily:"'DM Serif Display',serif", fontStyle:"italic", fontWeight:400 }}>ship faster</span>
            </h2>
          </div>
          <div style={{ display:"grid", gridTemplateColumns:"repeat(3,1fr)", gap:16 }}>
            {TESTIMONIALS.map(t => (
              <div key={t.name} className="testimonial-card">
                <div style={{ fontSize:28, color:t.color, marginBottom:16, opacity:0.6 }}>"</div>
                <p style={{ fontFamily:"'DM Serif Display',serif", fontSize:17, lineHeight:1.6, color:"rgba(255,255,255,0.85)", marginBottom:24, fontStyle:"italic" }}>
                  {t.quote}
                </p>
                <div style={{ display:"flex", alignItems:"center", gap:12 }}>
                  <div style={{ width:36, height:36, borderRadius:"50%", background:`${t.color}20`, border:`1px solid ${t.color}40`, display:"flex", alignItems:"center", justifyContent:"center", fontFamily:"'Space Mono',monospace", fontSize:12, color:t.color }}>{t.avatar}</div>
                  <div>
                    <div style={{ fontFamily:"'Syne',sans-serif", fontWeight:700, fontSize:13, color:"white" }}>{t.name}</div>
                    <div style={{ fontFamily:"'Space Mono',monospace", fontSize:9, color:"rgba(255,255,255,0.3)" }}>{t.role}</div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── PRICING ────────────────────────────────────────────────────── */}
      <section style={{ padding:"120px 48px", background:"rgba(255,255,255,0.01)", borderTop:"1px solid rgba(255,255,255,0.05)" }}>
        <div style={{ maxWidth:900, margin:"0 auto", textAlign:"center" }}>
          <span className="tag" style={{ marginBottom:20, display:"inline-block" }}>Pricing</span>
          <h2 style={{ fontFamily:"'Syne',sans-serif", fontWeight:800, fontSize:"clamp(32px,4vw,52px)", letterSpacing:"-0.02em", marginBottom:16 }}>
            Free while in beta.<br /><span style={{ color:ACCENT }}>Always founder-first.</span>
          </h2>
          <p style={{ fontFamily:"'Space Mono',monospace", fontSize:11, color:"rgba(255,255,255,0.35)", lineHeight:1.8, marginBottom:56, maxWidth:520, margin:"0 auto 56px" }}>
            Full access to every feature during beta. No credit card. No limits. We'll always have a generous free tier.
          </p>

          <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:16, maxWidth:700, margin:"0 auto" }}>
            {[
              {
                name:"Free",
                price:"$0",
                period:"forever",
                features:["Unlimited analyses","Health scoring","Burn simulator","OKR generator","Progress tracking"],
                cta:"Start for free",
                accent:false,
              },
              {
                name:"Pro",
                price:"$29",
                period:"/ month",
                features:["Everything in Free","PDF export","Pitch deck generator","Competitor deep-dive","Priority AI responses"],
                cta:"Coming soon",
                accent:true,
              },
            ].map(plan => (
              <div key={plan.name} style={{
                background: plan.accent ? `${ACCENT}08` : "rgba(255,255,255,0.02)",
                border: `1px solid ${plan.accent ? ACCENT+"30" : "rgba(255,255,255,0.08)"}`,
                borderRadius:20, padding:"36px 32px", textAlign:"left",
              }}>
                <div style={{ fontFamily:"'Space Mono',monospace", fontSize:9, color: plan.accent ? ACCENT : "rgba(255,255,255,0.3)", letterSpacing:"0.2em", textTransform:"uppercase", marginBottom:16 }}>{plan.name}</div>
                <div style={{ display:"flex", alignItems:"baseline", gap:6, marginBottom:24 }}>
                  <span style={{ fontFamily:"'Syne',sans-serif", fontWeight:800, fontSize:44, color:"white" }}>{plan.price}</span>
                  <span style={{ fontFamily:"'Space Mono',monospace", fontSize:11, color:"rgba(255,255,255,0.3)" }}>{plan.period}</span>
                </div>
                <div style={{ height:1, background:"rgba(255,255,255,0.06)", marginBottom:24 }} />
                <div style={{ display:"flex", flexDirection:"column", gap:10, marginBottom:28 }}>
                  {plan.features.map(f => (
                    <div key={f} style={{ display:"flex", alignItems:"center", gap:10 }}>
                      <span style={{ color: plan.accent ? ACCENT : "rgba(255,255,255,0.3)", fontSize:11 }}>✓</span>
                      <span style={{ fontFamily:"'Space Mono',monospace", fontSize:10, color:"rgba(255,255,255,0.55)" }}>{f}</span>
                    </div>
                  ))}
                </div>
                <button
                  onClick={() => !plan.accent && router.push("/login")}
                  style={{
                    width:"100%", padding:"13px", fontFamily:"'Space Mono',monospace",
                    fontSize:11, fontWeight:700, letterSpacing:"0.1em",
                    background: plan.accent ? "rgba(200,255,0,0.1)" : ACCENT,
                    color: plan.accent ? ACCENT : "#050505",
                    border: plan.accent ? `1px solid ${ACCENT}30` : "none",
                    borderRadius:10, cursor: plan.accent ? "default" : "pointer",
                    opacity: plan.accent ? 0.7 : 1,
                  }}
                >
                  {plan.cta} {!plan.accent && "→"}
                </button>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── CTA BOTTOM ─────────────────────────────────────────────────── */}
      <section className="grid-bg" style={{ padding:"140px 48px", textAlign:"center", position:"relative", overflow:"hidden" }}>
        <div style={{ position:"absolute", top:"50%", left:"50%", transform:"translate(-50%,-50%)", width:800, height:400, background:`radial-gradient(ellipse,rgba(200,255,0,0.06) 0%,transparent 70%)`, pointerEvents:"none" }} />
        <div style={{ position:"relative", zIndex:1 }}>
          <span className="tag" style={{ marginBottom:24, display:"inline-block" }}>Get started today</span>
          <h2 style={{ fontFamily:"'Syne',sans-serif", fontWeight:800, fontSize:"clamp(36px,5vw,72px)", letterSpacing:"-0.03em", lineHeight:1.05, marginBottom:24 }}>
            Stop guessing.<br />
            <span style={{ color:ACCENT, fontFamily:"'DM Serif Display',serif", fontStyle:"italic", fontWeight:400 }}>Start knowing.</span>
          </h2>
          <p style={{ fontFamily:"'Space Mono',monospace", fontSize:12, color:"rgba(255,255,255,0.35)", marginBottom:48, maxWidth:400, margin:"0 auto 48px", lineHeight:1.8 }}>
            Your startup health score is waiting. Free to use. No credit card. Results in 60 seconds.
          </p>
          <button className="cta-primary" style={{ fontSize:14, padding:"18px 40px" }} onClick={() => router.push("/login")}>
            ⬡ Analyze my startup for free
          </button>
        </div>
      </section>

      {/* ── FOOTER ─────────────────────────────────────────────────────── */}
      <footer style={{ borderTop:"1px solid rgba(255,255,255,0.06)", padding:"40px 48px", display:"flex", justifyContent:"space-between", alignItems:"center", flexWrap:"wrap", gap:16 }}>
        <div style={{ display:"flex", alignItems:"center", gap:10 }}>
          <div style={{ width:24, height:24, borderRadius:"50%", background:ACCENT, display:"flex", alignItems:"center", justifyContent:"center", fontSize:10 }}>⬡</div>
          <span style={{ fontFamily:"'Syne',sans-serif", fontWeight:800, fontSize:14, color:"white" }}>CORTIQ</span>
        </div>
        <span style={{ fontFamily:"'Space Mono',monospace", fontSize:9, color:"rgba(255,255,255,0.2)", letterSpacing:"0.1em" }}>
          © 2025 CORTIQ · AI STARTUP INTELLIGENCE
        </span>
        <div style={{ display:"flex", gap:20 }}>
          {["Privacy", "Terms", "Contact"].map(l => (
            <button key={l} style={{ fontFamily:"'Space Mono',monospace", fontSize:9, color:"rgba(255,255,255,0.25)", background:"none", border:"none", cursor:"pointer", letterSpacing:"0.1em" }}>{l}</button>
          ))}
        </div>
      </footer>
    </>
  );
}